[wokwi]
version = 1
elf = ".pio/build/esp32/firmware.elf"
firmware = ".pio/build/esp32/firmware.bin"

[paths]
# Copia a pasta 'data' para o sistema de arquivos do ESP32
# dentro do simulador.
filesystem = ".pio/build/esp32/littlefs.bin"

# Forward http://localhost:8180 to port 80 on the simulated ESP32:
[[net.forward]]
from = "localhost:8180"
to = "target:80"


